// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtsnspszgsmkqxuoqywm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0c25zcHN6Z3Nta3F4dW9xeXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTg0NzUsImV4cCI6MjA2NTIzNDQ3NX0.k4gAV17UWzVPCnHeXnqCfdJT12bTkK5ELKBuLvYIm_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);